# -*- mode: python ; coding: utf-8 -*-
# Портативный spec: только относительные пути, CWD — корень проекта.
from pathlib import Path

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
    ('plugins', 'plugins'),
    (r'locales\en\charset.json', r'locales\en'),
    (r'locales\en\messages.json', r'locales\en'),
    (r'locales\ja\charset.json', r'locales\ja'),
    (r'locales\ja\messages.json', r'locales\ja'),
    (r'locales\ru\charset.json', r'locales\ru'),
    (r'locales\ru\messages.json', r'locales\ru'),
    (r'locales\zh\charset.json', r'locales\zh'),
    (r'locales\zh\messages.json', r'locales\zh'),
    ('settings', 'settings'),
    ('resources', 'resources'),
    ('gui', 'gui'),
    ('core', 'core'),
    ],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'tkinter.scrolledtext',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'json',
        'logging',
        'pathlib',
        'collections',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'spellchecker',
        'tkinterdnd2',
        'core.decoder',
        'core.scanner',
        'core.extractor',
        'core.injector',
        'core.compression',
        'core.gba_support',
        'core.multi_charmap',
        'core.plugin_api',
        'core.tmx',
        'core.ml_classifier',
        'core.translation_validator',
        'core.translation_filler',
        'core.analyzer',
        'core.database',
        'core.encoding',
        'core.charset',
        'core.guide',
        'core.mbc',
        'core.rom_cache',
        'core.i18n',
        'core.machine_translation',
        'core.font_tiles',
        'core.font_ui',
        'core.playtest',
        'core.dte',
        'core.pointer_table',
        'core.textbox',
        'core.plugin_manager',
        'core.rom',
        'gui.main_window',
        'gui.font_tab',
        'gui.glyph_editor',
        'plugins.auto_detect'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'posix',
        'pwd',
        'grp',
        'fcntl',
        'resource',
        '_posixsubprocess',
        'java',
        'org',
        'vms_lib',
        '_winreg',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'cv2',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='GB2Text',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    cofile=None,
    icon='resources/app_icon.ico' if (Path('resources/app_icon.ico').exists()) else None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='GB2Text',
)
