# -*- mode: python ; coding: utf-8 -*-

import os

block_cipher = None

base_path = os.path.abspath('.')

a = Analysis(
    ['main.py'],
    pathex=[base_path],
    binaries=[],
    datas=[
        (os.path.join(base_path, 'VERSION'), '.'),
        (os.path.join(base_path, 'plugins'), 'plugins'),
        (os.path.join(base_path, 'locales'), 'locales'),
        (os.path.join(base_path, 'guides'), 'guides'),
        (os.path.join(base_path, 'resources'), 'resources'),
    ],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'tkinter.scrolledtext',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'json',
        're',
        'logging',
        'pathlib',
        'collections',
        'unicodedata',
        'core.decoder',
        'core.scanner',
        'core.extractor',
        'core.injector',
        'core.compression',
        'core.gba_support',
        'core.multi_charmap',
        'core.plugin_api',
        'core.tmx',
        'core.ml_classifier',
        'core.translation_validator',
        'core.translation_filler',
        'core.analyzer',
        'core.database',
        'core.encoding',
        'core.charset',
        'core.guide',
        'core.mbc',
        'core.rom_cache',
        'core.i18n',
        'core.machine_translation',
        'core.constants',
        'core.rom',
        'core.plugin',
        'core.plugin_manager',
        'plugins.auto_detect',
        'plugins.generic',
        'plugins.gba_fft_advance',
        'plugins.gba_pokemon',
        'plugins.gba_fire_emblem',
        'plugins.gba_zelda_tmc',
        'plugins.gba_ff4_advance',
        'plugins.gba_ff5_advance',
        'plugins.gba_ff6_advance',
        'plugins.gba_castlevania',
        'plugins.gba_castlevania_hod',
        'plugins.gba_castlevania_ctm',
        'plugins.gba_mario_luigi_ss',
        'plugins.gba_wario_land_4',
        'plugins.gba_astro_boy',
        'plugins.gba_metroid_fusion',
        'plugins.gba_megaman_battle_network',
        'plugins.gba_ct_special_forces',
        'plugins.gba_custom_robo_gx',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'posix',
        'pwd',
        'grp',
        'fcntl',
        'resource',
        '_posixsubprocess',
        'java',
        'org',
        'vms_lib',
        '_winreg',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'PIL',
        'cv2',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='GB2Text-Debug',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    cofile=None,
    icon='resources/app_icon.ico' if os.path.exists(os.path.join(base_path, 'resources', 'app_icon.ico')) else None,
    codesign_identity=None,
    entitlements_file=None,
)
